import Head from 'next/head'
import { Box, Center, Container, Text, Title } from '@mantine/core'
import { collection, doc, getDoc, getDocs } from 'firebase/firestore';
import { db } from '@/context/firebase';
import { HeaderMiddle } from '@/components/Layout/Navbar';
import { FundingRound } from '@/interfaces';
import Image from 'next/image';

export async function getServerSideProps(context: any) {
    let id = context.query.id;
    let pool = await getDoc(doc(db, `pools/${id}`));

    if (!pool) {
        throw new Error("No data found.");
    }

    let keyItems = pool.data();

    return {
        props: {
            keyItems,
        },
    };
}

export default function OpenRounds({ id, keyItems }: FundingRound) {
    return (
        <>
            <Head>
                <title>{keyItems.name} | Stockpile Grant Round</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderMiddle />
            <main>
                <Box
                    sx={{
                        width: "100%",
                        height: 665,
                        overflowX: "hidden",
                        "@media (max-width: 640px)": {
                            height: 365,
                        },
                    }}
                >
                    <Image src={keyItems.image} alt="Grant Round Image" height={350} />
                </Box>
            </main>
        </>
    )
}
