import Head from 'next/head'
import { Center, Container, Group, Text, Title, Tabs, Card, Box } from '@mantine/core'
import { collection, getDocs } from 'firebase/firestore';
import { db } from '@/context/firebase';
import styles from '../styles/Transitions.module.css'
import Cards from '../components/Dashboard/UserGrantsSection'
import AdCards from '@/components/Dashboard/AdminGrantsSection';
import Layout from '@/components/Layout/Layout';
import { TabsPanel } from '@mantine/core/lib/Tabs/TabsPanel/TabsPanel';
import { IconUserCircle } from '@tabler/icons-react';

import React from "react";

const gradient =
  'linear-gradient(100deg, #F75426 0%, rgba(247, 84, 38, 0) 100%)';

const styler = {
  border: '4px',
  backgroundImage: gradient,
  height: '4px',
  width: '100%',
  borderRadius: '6px', 
  margin: '0 auto',

  
};

const containerStyle = {
    display: 'flex',
    justifyContent: 'center',
    height: '340px',
  };

export async function getServerSideProps(context: any) {
    let fundraisers = await getDocs(collection(db, `grants`));

    if (!fundraisers) {
        throw new Error("No data found.");
    }

    let keyItems = fundraisers.docs.map((fundraisers) => {
        return {
            id: fundraisers.id,
            data: {
                ...fundraisers.data(),
            },
        };
    });

    return {
        props: {
            keyItems,
        },
    };

  
    

}


export default function Dashboard({ keyItems }: any) {
    return (
        
        <>
            <Head>
                <title>Stockpile Grants</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main>
                    <section>
                        <Center  >
                            <div className={styles.fadeInUp}>
                                <Title
                                    size={56}
                                    weight={900}
                                    
                                    sx={{
                                        fontFamily: 'Open Sans, Bold',
                                        
                                        "@media (max-width: 925px)": {
                                            
                                            textAlign: "center",
                                            fontSize: 42,
                                        },
                                        "@media (max-width: 520px)": {
                                            textAlign: "center",
                                            fontSize: 36,
                                        },
                                    }}
                                    >
                                    Dashboard{" "}
                                </Title>
                            </div>
                        </Center>
                        <Center mt="md">
                            <div className={styles.fadeInUp}>
                                <Text
                                    size="lg"
                                    color="dimmed"
                                    sx={(theme) => ({
                                        textAlign: "center",

                                        "@media (max-width: 925px)": {
                                            textAlign: "center",
                                            fontSize: 14,
                                        },

                                        "@media (max-width: 520px)": {
                                            textAlign: "center",
                                            fontSize: 10,
                                        },
                                    })}
                                >
                                    Manage Your User Account.
                                </Text>
                            </div>
                        </Center>
                    </section>
                    <section> 
                   <Tabs color="orange" defaultValue="Overview" >
                   <Tabs.List  grow position="center">
                   <Tabs.Tab value="Overview" >Overview</Tabs.Tab>
                   <Tabs.Tab value="Fundraisers" >Fundraisers</Tabs.Tab>
                   <Tabs.Tab value="Rounds" >Rounds</Tabs.Tab>
                   <Tabs.Tab value="Approvals" >Approvals</Tabs.Tab>
                  </Tabs.List>
                  <Tabs.Panel value="Overview" >
                    

                    
                   
                  <div style={containerStyle}>
                    <Card  padding="lg" radius="md" style={{
                       
                       display: 'flex',
                       alignItems: 'center',
                       justifyContent: 'center',
                       flexDirection: 'column',
                       marginRight: '20px',
                       
                       
                    }}>
                         
                        <IconUserCircle
                        size={40}
                        color={'#FF8B29'}
                        /> 
                        <Text style={{
                            fontFamily: 'Inter',
                            fontStyle:  'normal',
                            fontWeight: '300',
                            fontSize: '42px',
                            lineHeight: '100%',
                        }}> 0

                        
                        
                        <Group style={styler}>
                         </Group>
                         </Text>
                        <Text mt={10} style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 700,
                            fontSize: '18px',
                            lineHeight: '120%',
                          }}
                        >
                            TOTAL FUNDRAISERS
                        </Text>
                       
                       <Text mt={10} 
                           style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 400,
                            fontSize: '17px',
                            lineHeight: '100%',
                            width: '300px',
                          }}
                           >
                    Users have created 0 unique accounts from deploying a fundraiser or contributing! <br></br>
                    </Text> 
                    </Card>


                    <Card  padding="lg" radius="md" style={{
                       
                       display: 'flex',
                       alignItems: 'center',
                       justifyContent: 'center',
                       flexDirection: 'column',
                       marginRight: '20px',
                       
                       
                    }}>
                         
                        <IconUserCircle
                        size={40}
                        color={'#FF8B29'}
                        /> 
                        <Text style={{
                            fontFamily: 'Inter',
                            fontStyle:  'normal',
                            fontWeight: '300',
                            fontSize: '42px',
                            lineHeight: '100%',
                        }}> 1

                        
                        
                        <Group style={styler}>
                         </Group>
                         </Text>
                        <Text mt={10} style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 700,
                            fontSize: '18px',
                            lineHeight: '120%',
                          }}
                        >
                            TOTAL ROUNDS PARTICIPATED
                        </Text>
                       
                       <Text mt={10} 
                           style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 400,
                            fontSize: '17px',
                            lineHeight: '100%',
                            width: '300px',
                          }}
                           >
                    Users have created 0 unique accounts from deploying a fundraiser or contributing! <br></br>
                    </Text> 
                    </Card>

                    <Card  padding="lg" radius="md" style={{
                       
                       display: 'flex',
                       alignItems: 'center',
                       justifyContent: 'center',
                       flexDirection: 'column',
                       marginRight: '20px',
                       
                       
                    }}>
                         
                        <IconUserCircle
                        size={40}
                        color={'#FF8B29'}
                        /> 
                        <Text style={{
                            fontFamily: 'Inter',
                            fontStyle:  'normal',
                            fontWeight: '300',
                            fontSize: '42px',
                            lineHeight: '100%',
                        }}> 5

                        
                        
                        <Group style={styler}>
                         </Group>
                         </Text>
                        <Text mt={10} style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 700,
                            fontSize: '18px',
                            lineHeight: '120%',
                          }}
                        >
                            TOTAL CONTRIBUTIONS
                        </Text>
                       
                       <Text mt={10} 
                           style={{
                            fontFamily: 'Inter',
                            fontStyle: 'normal',
                            fontWeight: 400,
                            fontSize: '17px',
                            lineHeight: '100%',
                            width: '300px',
                          }}
                           >
                    Users have created 0 unique accounts from deploying a fundraiser or contributing! <br></br>
                    </Text> 
                    </Card>

                    </div>

                  </Tabs.Panel>
                  <Tabs.Panel value="Fundraisers">
                  <Container my={75}> 
                            <div className={styles.fadeInUp}> 
                                <Cards grants={keyItems} /> 
                            </div>
                        </Container>
                  </Tabs.Panel>
                  <Tabs.Panel value="Rounds">

                  </Tabs.Panel>
                  <Tabs.Panel value="Approvals">
                  <Container my={75}>
                            <div className={styles.fadeInUp}>
                                <AdCards grants={keyItems} />
                            </div>
                        </Container>
                  </Tabs.Panel>
                   </Tabs>
                    </section>
                </main>
            </Layout>
        </>
    )
}



    

