import Head from 'next/head'
import styles from "../styles/Transitions.module.css";
import { HeroBullets } from '@/components/Landing/Hero';
import Layout from '@/components/Layout/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Stockpile Grants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <section>
            <div className={styles.fadeInUp}>
              <HeroBullets />
            </div>
          </section>
        </main>
      </Layout>
    </>
  )
}
