import Head from 'next/head'
import { Center, Container, Text, Title } from '@mantine/core'
import { collection, getDocs } from 'firebase/firestore';
import { db } from '@/context/firebase';
import { TaskCard } from '@/components/Round/PoolInfoCard';
import Layout from '@/components/Layout/Layout';

export async function getServerSideProps() {
    let fundraisers = await getDocs(collection(db, `grants`));

    if (!fundraisers) {
        throw new Error("No data found.");
    }

    let keyItems = fundraisers.docs.map((fundraisers) => {
        return {
            id: fundraisers.id,
            data: {
                ...fundraisers.data(),
            },
        };
    });

    return {
        props: {
            keyItems,
        },
    };
}

export default function OpenRounds({ keyItems }: any) {
    return (
        <>
            <Head>
                <title>Open Grant Rounds | Stockpile Grants</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main>
                    <section>
                        <Center mt={25}>
                            <Title
                                size={56}
                                weight={900}
                                sx={{
                                    "@media (max-width: 925px)": {
                                        textAlign: "center",
                                        fontSize: 42,
                                    },
                                    "@media (max-width: 520px)": {
                                        textAlign: "center",
                                        fontSize: 36,
                                    },
                                }}
                            >
                                Discover Open{" "}
                                <Text
                                    component="span"
                                    size={56}
                                    weight={900}
                                    variant="gradient"
                                    gradient={{ from: "orange", to: "red" }}
                                    inherit
                                    sx={{
                                        "@media (max-width: 925px)": {
                                            textAlign: "center",
                                            fontSize: 42,
                                        },
                                        "@media (max-width: 520px)": {
                                            textAlign: "center",
                                            fontSize: 36,
                                        },
                                    }}
                                >
                                    Grant{" "}
                                </Text>
                                Rounds.
                            </Title>
                        </Center>
                        <Center mt="md">
                            <Text
                                size="lg"
                                color="dimmed"
                                sx={(theme) => ({
                                    textAlign: "center",

                                    "@media (max-width: 925px)": {
                                        textAlign: "center",
                                        fontSize: 14,
                                    },

                                    "@media (max-width: 520px)": {
                                        textAlign: "center",
                                        fontSize: 10,
                                    },
                                })}
                            >
                                View open rounds distributing grants for different causes.
                            </Text>
                        </Center>
                    </section>
                    <section>
                        <Container mt={50} mb={75}>
                            <TaskCard />
                        </Container>
                    </section>
                </main>
            </Layout>
        </>
    )
}
