import React from "react";
import { Container, Group } from "@mantine/core";
import FundraiserHead from "@/components/Grant/GrantsHead";
import FundraiserInfo from "@/components/Grant/GrantsInfo";
import FundraiserTabs from "@/components/Grant/GrantsTabs";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import Head from "next/head";
import { db } from "@/context/firebase";
import { HeaderMiddle } from "@/components/Layout/Navbar";
import { Grant } from "@/interfaces";

export const getServerSideProps = async ({ query }: any) => {
  let id = query.id;
  let fundraiser = await getDoc(doc(db, `grants/${id}`));
  if (!fundraiser) {
    throw new Error("No data found.");
  }

  let contributors = await getDocs(collection(db, `grants/${id}/contributors`));
  let comments = await getDocs(collection(db, `grants/${id}/comments`));

  let keyItems = fundraiser.data();

  let contributorItems = contributors.docs.map((contributor) => {
    return {
      id: contributor.id,
      data: {
        ...contributor.data(),
      },
    };
  });

  let commentItems = comments.docs.map((comment) => {
    return {
      id: comment.id,
      data: {
        ...comment.data(),
      },
    };
  });

  return {
    props: {
      id,
      keyItems,
      contributorItems,
      commentItems,
    },
  };
};

const Grant = ({ id, keyItems, contributorItems, commentItems }: Grant) => {
  return (
    <>
      <Head>
        <title>{keyItems.name} | Stockpile Grants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMiddle />
      <Container
        fluid
        mb="xl"
        sx={{
          maxWidth: 1800,
        }}
      >
        <FundraiserHead
          id={id}
          beneficiary={keyItems.beneficiary}
          pubkey={keyItems.pubkey}
          tag={keyItems.tag}
          image={keyItems.image}
          name={keyItems.name}
          tagline={keyItems.tagline}
          firstName={keyItems.firstName}
          lastName={keyItems.lastName}
          raised={keyItems.raised}
          contributions={keyItems.contributions}
          goal={keyItems.goal}
          time={keyItems.time}
        />
        <Group
          grow
          mt="lg"
          sx={{
            height: "100%",
            alignItems: "flex-start",
          }}
        >
          <Container size={"65%"} p="md">
            <FundraiserTabs
              contributors={contributorItems}
              description={keyItems.description}
              comments={commentItems}
            />
          </Container>

          <Container size={"33%"}>
            <FundraiserInfo
              pool={keyItems.pool}
              proposal={keyItems.proposal}
              time={keyItems.time}
              socials={{
                twitter: keyItems.twitter,
                website: keyItems.website,
                repo: keyItems.repo,
              }}
            />
          </Container>
        </Group>
      </Container>
    </>
  );
};

export default Grant;
